### ISSUE TITLE
Runtime error: use of undeclared identifier 'jpeg_read_icc_profile'

### ISSUE THREAD

**Issue by prettykingking** [discord/lilliput#189]
After updated the pkg to v1.3，when import the lilliput packge, the application exit with this error.

`opencv.cpp:254:9: error: use of undeclared identifier 'jpeg_read_icc_profile'`

OS: Mac OSX 12.3.1
Golang: 1.19.4

**Comment by skidder** [comment]
@prettykingking I suspect this is related to Lilliput supporting only Intel architecture dependencies on Mac OS X. This has been reported in a couple of Github issues:
 - https://github.com/discord/lilliput/issues/157

I'd like to close this out as a duplicate, but please feel to re-open if you think it's something else. Thanks again for reporting!

**Comment by prettykingking** [comment]
@skidder I am sure of that my Mac is Intel CPU. Strange thing, I see all dependancies are static archive. But there is an undeclared call.

**Comment by skidder** [comment]
Thanks @prettykingking for checking, I'll reopen this and take a look from my Intel Mac

**Comment by skidder** [comment]
@prettykingking I'm closing this out since we've chosen to support only Apple Silicon on MacOS. I'm sorry for any inconvenience this might cause.
